name: Example

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
    
concurrency:
  group: "example"
  cancel-in-progress: true
  

jobs:
  Example:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ref: ["master", "dev"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ matrix.ref }}

      - name: Install Node v14
        uses: actions/setup-node@v4
        with:
          node-version: 14

      - name: Install Dependencies
        run: yarn install

      - name: Run Config
        run: yarn run config

      - name: clone three.js ${{ matrix.ref }}
        run: git clone --single-branch -b ${{ matrix.ref }} --depth=1 https://github.com/mrdoob/three.js.git res

      - name: Generate examples
        run: |
          cd example-processor
          node index.js --unhandled-rejections=strict

      - name: Generate Config
        run: node generateConfig.js --unhandled-rejections=strict

      - name: Commit changes 
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "automated: Examples generated (actions)"
          file_pattern: "."
          skip_dirty_check: false
          skip_fetch: false
