name: Example

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "0 0 * * *"
  push:
    
concurrency:
  group: "example"
  cancel-in-progress: true
  

jobs:
  Example:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     ref: ["master", "dev", "patch-v4"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        # with:
        #   ref: ${{ matrix.ref }}

      - name: Install Node v14
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install Dependencies
        run: yarn install
        

      - name: Run Config
        run: yarn run config

      - name: clone three.js #${{ matrix.ref }}
        run: git clone --single-branch -b dev --depth=1 https://github.com/mrdoob/three.js.git res

      - name: Generate examples
        run: |
          cd example-processor
          node index.js --unhandled-rejections=strict

      - name: Generate Config
        run: node generateConfig.js --unhandled-rejections=strict

      - name: Commit changes 
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "automated: Examples generated (actions)"
          file_pattern: "."
          skip_dirty_check: false
          skip_fetch: false
